# Generated by Django 3.0.7 on 2020-08-01 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='username',
            field=models.IntegerField(max_length=100),
        ),
    ]
