# Generated by Django 3.0.7 on 2020-08-02 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_auto_20200801_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='id_user',
            field=models.CharField(max_length=100),
        ),
    ]
