# Generated by Django 3.0.7 on 2020-08-02 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_auto_20200802_0158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='id_user',
            field=models.IntegerField(),
        ),
    ]
