# Generated by Django 3.0.7 on 2020-08-05 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0006_auto_20200802_0240'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='id_user',
            new_name='id_trabajo',
        ),
    ]
