# Generated by Django 3.0.7 on 2020-08-05 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0007_auto_20200805_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='id_trabajo',
            field=models.CharField(default=1, max_length=100),
        ),
    ]
