# Generated by Django 3.0.7 on 2020-08-05 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0010_auto_20200804_0441'),
        ('usuario', '0009_auto_20200805_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='cargo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persona.Personal'),
        ),
    ]
