# Generated by Django 3.0.7 on 2020-08-06 00:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0010_auto_20200804_0441'),
        ('usuario', '0011_auto_20200806_0000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persona.Personal'),
        ),
    ]
