# Generated by Django 3.0.8 on 2020-07-24 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('platos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='platos',
            old_name='region',
            new_name='ciudad',
        ),
        migrations.RenameField(
            model_name='platos',
            old_name='exclusivo',
            new_name='portada',
        ),
    ]
