# Generated by Django 3.0.8 on 2020-07-24 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platos', '0002_auto_20200724_0558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platos',
            name='imagen',
            field=models.ImageField(upload_to='images'),
        ),
    ]
