# Generated by Django 3.0.8 on 2020-07-31 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platos', '0003_auto_20200724_0750'),
    ]

    operations = [
        migrations.AddField(
            model_name='platos',
            name='precio',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
