# Generated by Django 3.0.7 on 2020-07-14 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('id_dni', models.IntegerField()),
                ('edad', models.IntegerField(default=False)),
                ('sexo', models.CharField(choices=[('femenino', 'FEMENINO'), ('masculino', 'MASCULINO'), ('otro', 'OTRO')], default='otro', max_length=100)),
                ('direc', models.CharField(default=False, max_length=100)),
                ('vip', models.BooleanField(default=False)),
                ('especif_vip', models.CharField(default=False, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('foto', models.ImageField(upload_to='pics')),
                ('id_dni', models.IntegerField()),
                ('edad', models.IntegerField()),
                ('sexo', models.CharField(choices=[('femenino', 'FEMENINO'), ('masculino', 'MASCULINO'), ('otro', 'OTRO')], default='otro', max_length=100)),
                ('telefono', models.IntegerField()),
                ('direc', models.CharField(max_length=100)),
                ('correo', models.CharField(max_length=50)),
                ('experiencia', models.BooleanField(default=False)),
                ('cap_esp', models.BooleanField(default=False)),
                ('cvv', models.FileField(upload_to='pics')),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ruc', models.IntegerField()),
                ('direc', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
            ],
        ),
    ]
