# Generated by Django 3.0.7 on 2020-07-15 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personal',
            name='cvv',
        ),
        migrations.RemoveField(
            model_name='personal',
            name='experiencia',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='sexo',
            field=models.CharField(choices=[('femenino', 'FEMENINO'), ('masculino', 'MASCULINO'), ('otro', 'Prefiero no decirlo')], default='otro', max_length=100),
        ),
        migrations.AlterField(
            model_name='personal',
            name='sexo',
            field=models.CharField(choices=[('femenino', 'FEMENINO'), ('masculino', 'MASCULINO'), ('otro', 'Prefiero no decirlo')], default='otro', max_length=100),
        ),
    ]
