# Generated by Django 3.0.8 on 2020-07-24 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0003_remove_personal_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='direc',
            field=models.CharField(default='No requiere delibery', max_length=100),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='especif_vip',
            field=models.CharField(default='Ninguna', max_length=100),
        ),
    ]
