# Generated by Django 3.0.7 on 2020-07-31 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0005_auto_20200728_0337'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='id_dni',
            new_name='dni',
        ),
        migrations.AddField(
            model_name='cliente',
            name='id_cliente',
            field=models.IntegerField(default='002'),
        ),
    ]
