# Generated by Django 3.0.8 on 2020-08-03 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0008_auto_20200731_0032'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal',
            name='cargo',
            field=models.CharField(choices=[('administrador', 'ADMINISTRADOR'), ('jefe de cocina', 'JEFE DE COCINA'), ('recepcionista', 'RECEPCIONISTA'), ('cajero', 'CAJERO'), ('mesero', 'MESERO'), ('cocinero', 'COCINERO'), ('otro', 'VARIOS')], default='otro', max_length=100),
        ),
        migrations.AddField(
            model_name='personal',
            name='imagen',
            field=models.ImageField(default='persona/sin_imagen.jpg', upload_to='persona'),
        ),
    ]
