# Generated by Django 3.0.7 on 2020-08-06 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0011_auto_20200806_0226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='cargo',
            field=models.CharField(choices=[('100', 'ADMINISTRADOR'), ('101', 'JEFE DE COCINA'), ('102', 'JEFE DE ALMACEN'), ('recepcionista', 'RECEPCIONISTA'), ('cajero', 'CAJERO'), ('mesero', 'MESERO'), ('bartender', 'BARTENDER'), ('cocinero', 'COCINERO'), ('200', 'VARIOS')], default='otro', max_length=100),
        ),
        migrations.AlterField(
            model_name='personal',
            name='id_trabajo',
            field=models.CharField(default=models.CharField(choices=[('100', 'ADMINISTRADOR'), ('101', 'JEFE DE COCINA'), ('102', 'JEFE DE ALMACEN'), ('recepcionista', 'RECEPCIONISTA'), ('cajero', 'CAJERO'), ('mesero', 'MESERO'), ('bartender', 'BARTENDER'), ('cocinero', 'COCINERO'), ('200', 'VARIOS')], default='otro', max_length=100), max_length=100),
        ),
    ]
