# Generated by Django 3.0.7 on 2020-08-06 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0013_auto_20200806_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='id_trabajo',
            field=models.CharField(max_length=100),
        ),
    ]
