# Generated by Django 3.0.7 on 2020-08-07 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0015_auto_20200806_2223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='id_cliente',
        ),
        migrations.AddField(
            model_name='personal',
            name='id_trabajo',
            field=models.CharField(default=210, max_length=100),
        ),
        migrations.AlterField(
            model_name='personal',
            name='password',
            field=models.CharField(default='sumaq123', max_length=50),
        ),
    ]
