# Generated by Django 3.0.7 on 2020-08-07 01:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('platos', '0004_platos_precio'),
        ('persona', '0016_auto_20200807_0043'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comanda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persona.Cliente')),
                ('plato_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='platos.Platos')),
            ],
        ),
    ]
