# Generated by Django 3.0.7 on 2020-08-07 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platos', '0004_platos_precio'),
        ('persona', '0017_comanda'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='comandas',
            field=models.ManyToManyField(through='persona.Comanda', to='platos.Platos'),
        ),
    ]
