# Generated by Django 3.0.7 on 2020-08-07 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0019_auto_20200807_0205'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='id_trabajo',
            field=models.CharField(default=222, max_length=100),
        ),
    ]
