# Generated by Django 3.0.8 on 2020-08-09 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0020_cliente_id_trabajo'),
        ('persona', '0020_cliente_id_cliente'),
    ]

    operations = [
    ]
