# Generated by Django 3.0.7 on 2020-08-12 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0022_remove_cliente_id_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='id_trabajo',
        ),
        migrations.RemoveField(
            model_name='personal',
            name='id_trabajo',
        ),
    ]
