# Generated by Django 3.0.7 on 2020-08-13 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0024_cliente_id_trabajo'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal',
            name='id_trabajo',
            field=models.CharField(default='100', max_length=100),
            preserve_default=False,
        ),
    ]
