# Generated by Django 3.0.7 on 2020-08-06 00:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comandas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formato',
            name='fecha_hoy',
            field=models.DateTimeField(default=datetime.date(2020, 8, 6)),
        ),
    ]
