# Generated by Django 3.0.7 on 2020-08-06 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comandas', '0002_auto_20200806_0000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formato',
            name='fecha_hoy',
        ),
    ]
