# Generated by Django 3.0.8 on 2020-08-07 03:51

import comandas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comandas', '0003_remove_formato_fecha_hoy'),
    ]

    operations = [
        migrations.AddField(
            model_name='formato',
            name='hora_marca',
            field=models.CharField(default=comandas.models.hora, max_length=50),
        ),
        migrations.AddField(
            model_name='formato',
            name='numero_comanda',
            field=models.IntegerField(default=comandas.models.numero),
        ),
    ]
