# Generated by Django 3.0.8 on 2020-08-07 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comandas', '0004_auto_20200806_2251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formato',
            name='numero_comanda',
        ),
    ]
