# Generated by Django 3.0.8 on 2020-08-07 05:04

import comandas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comandas', '0005_remove_formato_numero_comanda'),
    ]

    operations = [
        migrations.AddField(
            model_name='formato',
            name='numero_comanda',
            field=models.IntegerField(default=comandas.models.numero),
        ),
    ]
