# Generated by Django 3.0.8 on 2020-08-07 05:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comandas', '0006_formato_numero_comanda'),
    ]

    operations = [
        migrations.AddField(
            model_name='formato',
            name='fecha_hoy',
            field=models.CharField(default=datetime.date(2020, 8, 7), max_length=50),
        ),
    ]
