# Generated by Django 3.0.8 on 2020-08-09 08:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0022_remove_cliente_id_cliente'),
        ('comandas', '0008_auto_20200808_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formato',
            name='fecha_hoy',
            field=models.CharField(default=datetime.date(2020, 8, 9), max_length=50),
        ),
        migrations.AlterField(
            model_name='formato',
            name='id_camarero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='persona.Personal'),
        ),
    ]
