# Generated by Django 3.0.8 on 2020-08-09 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comandas', '0009_auto_20200809_0321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formato',
            name='id_camarero',
            field=models.CharField(max_length=100),
        ),
    ]
