# Generated by Django 3.0.8 on 2020-08-09 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0022_remove_cliente_id_cliente'),
        ('comandas', '0011_auto_20200809_0327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formato',
            name='id_camarero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='camarero', to='persona.Personal'),
        ),
    ]
