# Generated by Django 3.0.8 on 2020-08-10 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('platos', '0004_platos_precio'),
        ('comandas', '0012_auto_20200809_0401'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formato',
            name='id_platos',
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Num_platos', models.IntegerField(default=0)),
                ('id_platos', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='platos.Platos')),
            ],
        ),
        migrations.AddField(
            model_name='formato',
            name='id_pedido',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='comandas.Pedido'),
            preserve_default=False,
        ),
    ]
