# Generated by Django 3.0.8 on 2020-08-10 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comandas', '0013_auto_20200809_1919'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formato',
            name='id_pedido',
        ),
        migrations.AddField(
            model_name='formato',
            name='id_pedido',
            field=models.ManyToManyField(to='comandas.Pedido'),
        ),
    ]
