# Generated by Django 3.0.8 on 2020-08-10 00:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comandas', '0014_auto_20200809_1924'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formato',
            name='id_pedido',
        ),
        migrations.AddField(
            model_name='formato',
            name='id_pedido',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='comandas.Pedido'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pedido',
            name='id_platos',
            field=models.IntegerField(),
        ),
    ]
