# Generated by Django 3.0.8 on 2020-08-10 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comandas', '0015_auto_20200809_1930'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='id_platos',
            new_name='platos',
        ),
    ]
