# Generated by Django 3.0.8 on 2020-08-10 04:20

import comandas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comandas', '0018_auto_20200809_2124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formato',
            name='id_pedido',
        ),
        migrations.AddField(
            model_name='pedido',
            name='codigo',
            field=models.IntegerField(default=comandas.models.numero),
        ),
    ]
