# Generated by Django 3.0.8 on 2020-08-10 05:35

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comandas', '0019_auto_20200809_2320'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='Num_platos',
            new_name='num_platos',
        ),
        migrations.RemoveField(
            model_name='formato',
            name='id',
        ),
        migrations.AddField(
            model_name='formato',
            name='pedido_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='comandas.Pedido'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='formato',
            name='fecha_hoy',
            field=models.CharField(default=datetime.date(2020, 8, 10), max_length=50),
        ),
    ]
