# Generated by Django 3.0.7 on 2020-08-12 00:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comandas', '0020_auto_20200810_0035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formato',
            name='fecha_hoy',
            field=models.CharField(default=datetime.date(2020, 8, 12), max_length=50),
        ),
    ]
