# Generated by Django 3.0.8 on 2020-08-12 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('platos', '0004_platos_precio'),
        ('comandas', '0022_auto_20200812_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formato',
            name='pedido_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='platos.Platos'),
        ),
    ]
