# Generated by Django 3.0.8 on 2020-08-12 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comandas', '0024_ingredient_instruction_recipe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instruction',
            name='recipe',
        ),
        migrations.DeleteModel(
            name='Ingredient',
        ),
        migrations.DeleteModel(
            name='Instruction',
        ),
        migrations.DeleteModel(
            name='Recipe',
        ),
    ]
