# Generated by Django 3.0.8 on 2020-08-12 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0022_remove_cliente_id_cliente'),
        ('platos', '0004_platos_precio'),
        ('comandas', '0027_pedido_num_platos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formato',
            name='id_camarero',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='camarero', to='persona.Personal'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='platos',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='platos.Platos'),
        ),
    ]
