# Generated by Django 3.0.8 on 2020-08-12 19:52

import comandas.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0022_remove_cliente_id_cliente'),
        ('comandas', '0030_auto_20200812_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formato',
            name='hora_marca',
            field=models.CharField(blank=True, default=comandas.models.hora, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='formato',
            name='id_camarero',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='camarero', to='persona.Personal'),
        ),
        migrations.AlterField(
            model_name='formato',
            name='numero_comanda',
            field=models.IntegerField(blank=True, default=comandas.models.numero, null=True),
        ),
    ]
