# Generated by Django 3.0.8 on 2020-08-12 20:04

import comandas.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('platos', '0004_platos_precio'),
        ('comandas', '0032_auto_20200812_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formato',
            name='fecha_hoy',
            field=models.CharField(blank=True, default=datetime.date(2020, 8, 12), max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='formato',
            name='numero_comensales',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='formato',
            name='numero_mesa',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='codigo',
            field=models.IntegerField(blank=True, default=comandas.models.numero, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='num_platos',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='platos',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='platos.Platos'),
        ),
    ]
