# Generated by Django 3.0.8 on 2020-08-12 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comandas', '0033_auto_20200812_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='formato',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='comandas.Formato'),
        ),
    ]
