# Generated by Django 3.0.8 on 2020-08-13 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comandas', '0034_auto_20200812_1541'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='formato',
            new_name='vincu',
        ),
    ]
