# Generated by Django 3.0.8 on 2020-08-13 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comandas', '0021_auto_20200812_0013'),
        ('comandas', '0036_auto_20200812_1936'),
    ]

    operations = [
    ]
