# Generated by Django 3.0.8 on 2020-08-13 02:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comandas', '0037_merge_20200812_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formato',
            name='fecha_hoy',
            field=models.CharField(blank=True, default=datetime.date(2020, 8, 12), max_length=50, null=True),
        ),
    ]
