# Generated by Django 3.0.8 on 2020-08-13 02:45

import comandas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comandas', '0038_auto_20200812_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formato',
            name='hora_marca',
            field=models.CharField(default=comandas.models.hora, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='formato',
            name='numero_comanda',
            field=models.IntegerField(default=comandas.models.numero, null=True),
        ),
    ]
