# Generated by Django 3.0.8 on 2020-08-13 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('platos', '0004_platos_precio'),
        ('comandas', '0039_auto_20200812_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='formato',
            name='pedido_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='platos.Platos'),
            preserve_default=False,
        ),
    ]
