# Generated by Django 3.0.7 on 2020-08-13 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comandas', '0042_auto_20200813_0755'),
        ('comandas', '0042_auto_20200813_0828'),
    ]

    operations = [
    ]
