
# Generated by Django 3.0.7 on 2020-08-07 04:51

# Generated by Django 3.0.8 on 2020-08-07 04:24


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [

        ('persona', '0020_cliente_id_trabajo'),
        ('persona', '0020_cliente_id_cliente'),

    ]

    operations = [
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora', models.DateField()),
                ('cuenta', models.IntegerField()),
                ('met_de_pago', models.CharField(choices=[('tarjeta', 'TARJETA'), ('efectivo', 'EFECTIVO')], default='efectivo', max_length=100)),
                ('descuento', models.CharField(choices=[('vip', 'CLIENTE VIP: 40%'), ('golden', 'TARJETA DORADA: 25%'), ('festivo', 'DIA FESTIVO: 15%'), ('cumpleaños', 'TU CUMPLEAÑOS: 20%'), ('aniversario', 'ANIVERSARIO DE CASA: 50%'), ('ninguno', 'ninguno')], default='ninguno', max_length=100)),
                ('total_pagar', models.IntegerField()),
                ('cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='persona.Cliente')),
                ('comanda', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='persona.Comanda')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=100)),
                ('telefono', models.IntegerField()),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('numero_mesa', models.IntegerField()),
                ('numero_personas', models.CharField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), ('mas de 5', 'Mas de 5')], default=1, max_length=100)),
                ('reporte', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='reporte.Reporte')),
            ],
        ),
    ]
