# Generated by Django 3.0.7 on 2020-08-12 05:43

from django.db import migrations, models
import reporte.models


class Migration(migrations.Migration):

    dependencies = [
        ('reporte', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='reporte',
        ),
        migrations.AddField(
            model_name='reserva',
            name='num_reserva',
            field=models.IntegerField(default=reporte.models.numero),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='numero_personas',
            field=models.IntegerField(default=1),
        ),
    ]
